version: '3.9'

services:
  web:
    build: .
    command: python /web_master/manage.py runserver 0.0.0.0:8000
    volumes:
     - .:/web_master
    ports:
     - '8000:8000'
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=django-insecure-4cm7z!6$$ftyilq!f(g&10@8*1773j@&$$m&u+(56-olk2goqyyc"
      - "DJANGO_DEBUG=True"

  db:
    image: postgres:13
    volumes:
     - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

volumes:
  postgres_data: